"""Small commercial taxonomy for sales-oriented Profile Activity claims."""
TAXONOMY_VERSION = 'DASTABASE_COMMERCIAL_V1'

CATEGORIES = frozenset({
    'MANUFACTURING', 'CONSTRUCTION', 'WHOLESALE_DISTRIBUTION', 'RETAIL',
    'TRANSPORT_LOGISTICS', 'HOSPITALITY_TOURISM', 'PROFESSIONAL_SERVICES',
    'IT_TECHNOLOGY', 'HEALTHCARE', 'EDUCATION', 'REAL_ESTATE',
    'ENERGY_ENVIRONMENT', 'AGRICULTURE_FOOD', 'OTHER',
})
